name: eclipse
base: core18

version: '2020-06'
summary: Extensible Tool Platform and Java IDE
description:
  Eclipse provides IDEs and platforms for nearly every language and architecture.
  We are famous for our Java IDE, C/C++, JavaScript and PHP IDEs built on extensible
  platforms for creating desktop, Web and cloud IDEs. These platforms deliver the most
  extensive collection of add-on tools available for software developers.

grade: stable
confinement: classic

architectures:
  - build-on: amd64

apps:
  eclipse:
    command: eclipse -configuration ${SNAP_USER_DATA}/${SNAP_ARCH}/configuration

parts:
  eclipse:
    plugin: dump
    source: http://ftp.halifax.rwth-aachen.de/eclipse/technology/epp/downloads/release/$SNAPCRAFT_PROJECT_VERSION/R/eclipse-java-$SNAPCRAFT_PROJECT_VERSION-R-linux-gtk-x86_64.tar.gz
    source-checksum: "sha512/2b471ba974f0632e2e8198c77a4a85cd126bbc1c2e9313e388997820181b39124cb4443c8aac8af0bbb7973bcb2e55303b566f91f58f35e1bf9eb3ea8f5289ec"
    override-build: |
      snapcraftctl build
      # Add these missing libraries to DT_NEEDED
      patchelf \
        --add-needed libffi.so.6 \
        --add-needed libgdk_pixbuf-2.0.so.0 \
        --add-needed libgio-2.0.so.0 \
        --add-needed libglib-2.0.so.0 \
        --add-needed libgmodule-2.0.so.0 \
        --add-needed libgobject-2.0.so.0 \
        --add-needed libsecret-1.so.0 \
        eclipse
    build-packages:
      - patchelf
    stage-packages:
      - libffi6
      - libgdk-pixbuf2.0-0
      - libglib2.0-0
      - libsecret-1-0
